modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="better_campfire"
version="${file.jarVersion}"
displayName="Better campfire"
authors="daizuch"
description='''
More realistic setup for a campfire.  
'''

[[dependencies.Bettercampfire]]
   modId="minecraft"
   mandatory=true
   # This version range declares a minimum of the current minecraft version up to but not including the next major version
   versionRange="[1.16.5,1.17)"
   ordering="NONE"
   side="BOTH"
